// src/constants/suggestions.js
const allSuggestions = [
  { name:'acesso', link: '/cadastro' },
  { name: 'almofadas', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'autenticação', link: '/autenticacao' },
  { name: 'bolsas', link: '/produtos?categoria=bolsas' },
  { name: 'brinquedos', link: '/produtos?categoria=brinquedos' },
  { name: 'cadastro', link: '/cadastro' },
  { name: 'cafeteira', link: '/produtos?categoria=eletrodomesticos' },
  { name: 'calçados', link: '/produtos?categoria=calçados' },
  { name: 'cama, mesa e banho', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'camping', link: '/produtos?categoria=camping' },
  { name: 'casa', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'chave de fenda', link: '/produtos?categoria=ferramentas' },
  { name: 'churrasco', link: '/produtos?categoria=churrasco' },
  { name: 'chuteira', link: '/produtos?categoria=calcados' },
  { name: 'contato', link: '/contato' },
  { name: 'eletrodomésticos', link: '/produtos?categoria=eletrodomésticos' },
  { name: 'esqueci minha senha', link: '/autenticacao' },
  { name: 'ferramentas', link: '/produtos?categoria=ferramentas' },
  { name: 'fritadeira', link: '/produtos?categoria=eletrodomesticos' },
  { name: 'home', link: '/' },
  { name: 'informática', link: '/produtos?categoria=informática' },
  { name: 'lençol', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'login', link: '/login' },
  { name: 'martelo', link: '/produtos?categoria=ferramentas' },
  { name: 'mochila', link: '/produtos?categoria=bolsas' },
  { name: 'perfumes', link: '/produtos?categoria=perfumes' },
  { name: 'política de privacidade', link: '/politica-privacidade' },
  { name: 'pratos', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'primeiro acesso', link: '/cadastro' },
  { name: 'registro', link: '/cadastro' },
  { name: 'senha', link: '/login' },
  { name: 'sobre nós', link: '/sobre' },
  { name: 'talheres', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'tapetes', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'tênis', link: '/produtos?categoria=calcados' },
  { name: 'termos de uso', link: '/termos-uso' },
  { name: 'toalha', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'toalha', link: '/produtos?categoria=cama-mesa-banho' },
  { name: 'tomadas', link: '/produtos?categoria=ferramentas' },
  { name: 'topperware', link: '/produtos?categoria=utensílios' },
  { name: 'utensílios', link: '/produtos?categoria=utensílios' },
  { name: 'vasilas', link: '/produtos?categoria=utensílios' },
  { name: 'ventilador', link: '/produtos?categoria=eletrodomesticos' },
  
  
  ];
  
export default allSuggestions